name: '[CI] Continuous Integration'

# Sempre que tiver commit ou um PR for aberto
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Common CI steps
      - uses: actions/checkout@v3
      #############
      - name: 'Start degug'
        run: |
          echo 'vamo gurizadaaaaaaa'
          echo 'Começando o CI Crud com Qualidade'
          echo 'Vamo lá!'
      - name: 'Install dependencies'
        # run: 'npm ci'
        run: 'npm install'
      - name: 'Lint'
        run: 'npm run lint'
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      # Common CI steps
      - uses: actions/checkout@v3
      #############
      - name: 'Install Dependencies'
        run: 'npm install' # 'npm ci'
      - name: 'Test Cypress'
        run: 'npm run test'
